(specifications->manifest
  '("python"
    "python-pytest"
    "python-requests"
    "python-fuzzywuzzy"
    "python-pyalex"
    "python-bibtexparser-1"
    "python-beautifulsoup4"
    "python-pylatexenc"
    "python-grobid-client-python"))
