(specifications->manifest
  '("python"
    "python-pytest"
    "python-httpx"
    "python-fuzzywuzzy"
    "python-bibtexparser-1"
    "python-beautifulsoup4"
    "python-pylatexenc"
    "python-grobid-client-python"
    "python-ruff"
    "node-pyright"))
